# Generated by Django 3.1.7 on 2021-03-02 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_questionmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='substreammodel',
            old_name='course',
            new_name='stream',
        ),
    ]
