# Generated by Django 3.1.7 on 2021-03-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20210302_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='answer',
            field=models.CharField(choices=[('Option 1', '1'), ('Option 2', '2'), ('Option 3', '3'), ('Option 4', '4')], max_length=20),
        ),
    ]
