# Generated by Django 3.1.7 on 2021-03-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_auto_20210303_1109'),
        ('counsellor_agent', '0004_auto_20210304_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('sub_streams', models.ManyToManyField(to='exam.SubStreamModel')),
            ],
        ),
    ]
