# Generated by Django 3.1.7 on 2021-03-04 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0006_auto_20210303_1109'),
        ('counsellor_agent', '0005_collegemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentnotification',
            name='counsellor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='counsellor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agentnotification',
            name='score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exam.scoremodel'),
        ),
        migrations.AlterField(
            model_name='collegemodel',
            name='sub_streams',
            field=models.ManyToManyField(to='exam.SubStreamModel', verbose_name='Courses'),
        ),
        migrations.AlterField(
            model_name='counsellornotification',
            name='score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exam.scoremodel'),
        ),
        migrations.CreateModel(
            name='StudentNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notified_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_agency', to=settings.AUTH_USER_MODEL)),
                ('collegeModel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='counsellor_agent.collegemodel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
