# Generated by Django 3.1.7 on 2021-03-04 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counsellor_agent', '0006_auto_20210304_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentnotification',
            old_name='collegeModel',
            new_name='college',
        ),
    ]
